import { fromFileUrl } from "@std/path";
import { canonicalUtf8FromBytes } from "../src/domain/canonical-utf8.ts";
import { ValidationError } from "../src/domain/errors.ts";

export const KIT_ASSET_BINDINGS = [
  { relativePath: "models/CoffeeMachine.mo" },
  { relativePath: "models/CoffeeMachine.parameters.json" },
  { relativePath: "scenarios/heat-up-nominal.json" },
  { relativePath: "models/LinearThermalRamp.mo" },
  { relativePath: "scenarios/linear-ramp-nominal.json" },
] as const;

export type KitAssetRelativePath = typeof KIT_ASSET_BINDINGS[number]["relativePath"];

export const REPOSITORY_ROOT = new URL("../", import.meta.url);
export const GENERATED_MODULE = new URL("../src/kits/generated-kit-assets.ts", import.meta.url);

const encoder = new TextEncoder();

export class GeneratedKitAssetsError extends Error {
  constructor(
    readonly code: string,
    readonly context: Record<string, unknown>,
    readonly recovery: string,
  ) {
    super(code);
    this.name = "GeneratedKitAssetsError";
  }

  toJSON() {
    return { code: this.code, context: this.context, recovery: this.recovery };
  }
}

export interface GeneratedKitAssetsPaths {
  root?: URL;
  output?: URL;
}

if (import.meta.main) {
  try {
    await main(Deno.args);
  } catch (error) {
    console.error(JSON.stringify(toMachineReadableError(error)));
    Deno.exitCode = 1;
  }
}

async function main(args: readonly string[]): Promise<void> {
  if (args.length > 1 || (args.length === 1 && args[0] !== "--check")) {
    throw failure(
      "invalid_generated_kit_assets_command",
      { arguments: [...args] },
      "Use no argument to generate the TypeScript bindings, or `--check` to verify them without writing.",
    );
  }
  if (args[0] === "--check") {
    await checkGeneratedKitAssets();
    return;
  }
  await writeGeneratedKitAssets();
}

export async function renderGeneratedKitAssets(
  root: URL = REPOSITORY_ROOT,
): Promise<Uint8Array> {
  const directory = asDirectoryUrl(root);
  const entries: string[] = [];
  for (const binding of KIT_ASSET_BINDINGS) {
    const path = new URL(binding.relativePath, directory);
    const raw = await Deno.readFile(path);
    let canonical: { source: string };
    try {
      canonical = await canonicalUtf8FromBytes(raw, binding.relativePath);
    } catch (error) {
      throw failure(
        "generated_kit_asset_noncanonical_utf8",
        {
          path: binding.relativePath,
          message: error instanceof Error ? error.message : String(error),
        },
        "Store each qualified kit asset as canonical UTF-8, then regenerate the TypeScript bindings.",
      );
    }
    entries.push(`  ${JSON.stringify(binding.relativePath)}: ${JSON.stringify(canonical.source)},`);
  }
  const source = [
    "// Generated by scripts/generate-kit-assets.ts. Do not edit.",
    "",
    "export const generatedKitAssetText = {",
    ...entries,
    "} as const;",
    "",
  ].join("\n");
  return encoder.encode(source);
}

export async function checkGeneratedKitAssets(
  paths: GeneratedKitAssetsPaths = {},
): Promise<void> {
  const output = paths.output ?? GENERATED_MODULE;
  const expected = await renderGeneratedKitAssets(paths.root ?? REPOSITORY_ROOT);
  let actual: Uint8Array;
  try {
    actual = await Deno.readFile(output);
  } catch (error) {
    throw failure(
      "generated_kit_assets_missing",
      {
        output: fromFileUrl(output),
        message: error instanceof Error ? error.message : String(error),
      },
      "Run `deno task kit-assets:generate` and review the generated TypeScript bindings.",
    );
  }
  if (!bytesEqual(expected, actual)) {
    throw failure(
      "generated_kit_assets_stale",
      { output: fromFileUrl(output) },
      "Review the qualified kit assets, then run `deno task kit-assets:generate`.",
    );
  }
}

export async function writeGeneratedKitAssets(
  paths: GeneratedKitAssetsPaths = {},
): Promise<void> {
  const output = paths.output ?? GENERATED_MODULE;
  await Deno.writeFile(output, await renderGeneratedKitAssets(paths.root ?? REPOSITORY_ROOT));
}

function asDirectoryUrl(root: URL): URL {
  return root.href.endsWith("/") ? root : new URL(`${root.href}/`);
}

function bytesEqual(left: Uint8Array, right: Uint8Array): boolean {
  return left.byteLength === right.byteLength &&
    left.every((byte, index) => byte === right[index]);
}

function failure(
  code: string,
  context: Record<string, unknown>,
  recovery: string,
): GeneratedKitAssetsError {
  return new GeneratedKitAssetsError(code, context, recovery);
}

function toMachineReadableError(error: unknown): Record<string, unknown> {
  if (error instanceof GeneratedKitAssetsError) return error.toJSON();
  if (error instanceof ValidationError) {
    return {
      code: "generated_kit_assets_validation_failed",
      context: { message: error.message },
      recovery: "Fix the qualified kit asset bytes, then rerun the generator.",
    };
  }
  return {
    code: "generated_kit_assets_unexpected_failure",
    context: { message: error instanceof Error ? error.message : String(error) },
    recovery: "Inspect the underlying error before retrying the generator.",
  };
}
