name: Check

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  deno:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.9.2
      - run: deno task check
      - run: deno task fmt
      - run: deno task lint
      - run: deno task test

  openmodelica:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build --target verify .
